[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python run.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
ENVIRONMENT = "production"
DEBUG = "false"
LOG_LEVEL = "INFO"
PORT = "8000"

# File processing
UPLOAD_DIR = "./enterprise_uploads"
VECTOR_STORE_PATH = "./enterprise_chroma_db"
MAX_FILE_SIZE = "104857600"
SUPPORTED_FORMATS = "pdf,docx,xlsx,csv,txt,json,pptx"

# Enterprise features
ENTERPRISE_MAX_DOCUMENTS = "10000"
DEFAULT_MAX_DOCUMENTS = "10"
RAG_SIMILARITY_THRESHOLD = "0.6"
CHUNK_SIZE = "2000"
CHUNK_OVERLAP = "400"
LLM_MODEL = "gpt-4"
LLM_TEMPERATURE = "0.1"
EMBEDDING_MODEL = "text-embedding-ada-002"

# Security
JWT_ALGORITHM = "HS256"
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = "480"
BCRYPT_ROUNDS = "12"

# Performance
REDIS_CACHE_TTL = "3600"
CONVERSATION_HISTORY_LIMIT = "20"
ENABLE_QUERY_CACHE = "true"
ENABLE_RESULT_PAGINATION = "true"
MAX_RESULTS_PER_PAGE = "50"

# Enterprise Analytics
ENABLE_ADVANCED_ANALYTICS = "true"
ENABLE_AUTO_REPORTS = "true"
ENABLE_CHARTS = "true"
CHART_THEME = "plotly_white"

# Multi-language
ENABLE_MULTI_LANGUAGE = "true"
DEFAULT_LANGUAGE = "en"
SUPPORTED_LANGUAGES = "en,es,fr,de"

# Security features
ENABLE_AUDIT_LOG = "true"
ENABLE_DATA_EXPORT = "true"
ENABLE_API_RATE_LIMITING = "true"
RATE_LIMIT_PER_MINUTE = "60"

# LangChain
LANGCHAIN_TRACING_V2 = "true"
LANGCHAIN_PROJECT = "enterprise-ai-brain"

# CORS (will be updated with actual domain)
CORS_ORIGINS = "https://your-frontend-domain.com,http://localhost:3000"